version: "3.2"
services:
    webwp:
         container_name: wp
         hostname: wp
         image: wordpress:latest
         ports:
           - "8085:80"
         links:
           - db
         volumes:
           - ./html/wordpress:/var/www/html
           - ./files:/files
           - ./php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    db:
        container_name: mariadb-wp
        hostname: mariadb-wp
        image: mariadb
        ports:
          - "3336:3306"
        environment:
          MYSQL_DATABASE: wordpressdb
          MYSQL_USER: adminwp
          MYSQL_PASSWORD: adminwp
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - wp-db:/var/lib/mysql
          - ./files:/files
        networks:
          - default

volumes:
    wp-db:
