FROM php:7.2-fpm
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

web:
        container_name: webapp
        hostname: webapp
        build: './php/'
        environment:
          - ALLOW_OVERRIDE=true
        ports:
          - "8081:80"
          - "4000:443"
        links:
          - db
        volumes:
          - ./html/moodle:/var/www/html
          - ./file:/files

